daengnyang-market/daengnyang-market-client

src/components/common/TopNavBar/TopMainNav.jsx
src/components/common/TopNavBar/TopTitleNav.jsx

- 용이한 재사용을 위해 변경하였습니다.
- TopChatNav의 파일명이 TopTitleNav로 변경됩니다.
- TopMainNav에 title=''을 통해 제목을 전달할 수 있습니다.
`<TopMainNav title='안녕' />`
- TopTitleNav에 title=''을 통해 제목을 전달할 수 있습니다.
`<TopTitleNav title='안녕' />`
close : #59

design: TopMainNav, TopTitleNav의 title을 props로 받도록 변경 (#59)

---

src/components/common/Post/Post.jsx

- Post 컴포넌트의 WrapperDiv에 margin-bottom 20px 추가를 위해서
- MoreSmallIcon의 position 수정을 위해서
close : #60

design: WrapperDiv에 margin-bottom 추가 및 MoreSmallIcon에 position 수정 (#60)

---

src/pages/FeedPage/FeedPage.jsx

- 팀원분들께서 작업해주신 컴포넌트를 합쳐 전체 페이지 세부 Style을 수정했습니다. 
- useState 사용하여 팔로잉한 사람들이 게시물을 가지고 있을때 (true일때) 는 피드 리스트가 나오게 구현했고, 반대의 경우(false) 빈 페이지가 뜨게 구현했습니다.
- 페이지 내 아이콘이 정 가운데에 위치하게 하기 위해 빈 페이지일때는 `<ContentsLayout>`을 사용하지 않았습니다
close : #38

design: 피드 페이지 퍼블리싱 (#38)

---

src/pages/FollowListPage/FollowListPage.jsx

- 팔로우 목록 페이지를 구현했습니다.
- 팔로우 목록이 뜨도록 구현했습니다.
- 팔로워 목록 페이지, 팔로잉 목록 페이지는 UI가 동일하므로 본 페이지를 재사용할 예정입니다.
close : #46

design: 팔로우 목록 페이지 퍼블리싱 (#46)

---

src/components/common/Comment/Comment.jsx
src/pages/PostDetailPage/PostComment.jsx
src/pages/PostDetailPage/PostDetailPage.jsx

- 게시물 상세 페이지 UI 를 렌더링 하기위해서 퍼블리싱을 하였다.
- 게시물 상세 페이지가 피그마 시안에 맞추어 렌더링 될 것이다.
- 확인부탁드려요오~
close : #78

design: 게시물 상세 페이지 퍼블리싱 (#78)

---

src/components/carousel/PaginationCarousel/PaginationCarousel.jsx

- 페이지네이션 캐러셀을 만들었습니다.
- 2.5초마다 자동으로 페이지가 넘어가는 캐러셀을 사용할 수 있습니다.
- 마우스로 직접 페이지를 넘길수도 있습니다.
close : #91

design: Pagination Carousel 컴포넌트 구현 (#91)

---

src/components/common/ProfileImage/ProfileImage.jsx

- 확장성을 위해 ProfileImage의 스타일 커스텀 기능을 추가했습니다.
- height: auto에서 문제가 있어 height를 width size와 동일한 px로 적용하도록 했습니다.
- height가 width의 사이즈와 동일하게 적용됩니다.
- border의 기본값이 0.5px로 변경됩니다.
- borderWeight 값을 전달해서 테두리 굵기 커스텀이 가능합니다.
- isPointer를 전달해서 마우스 커서를 포인터로 할지, 디폴트로 할지 설정이 가능합니다.
- isPointer는 boolean 값으로 전달해야 하며 기본값은 `true(포인터 커서)`입니다.
- isPointer 값이 true일 경우 포인터 커서로, false일 경우 디폴트 커서로 적용됩니다.
close : #93

design: ProfileImage 컴포넌트 스타일 커스텀 기능 추가 (#93)

---

src/components/common/HiddenMenu/HiddenMenu.jsx

- 리스트 아이템을 개발자에게 직접 받아 HiddenMenu 리스트를 구성할 수 있도록 컴포넌트를 확장하였습니다.
- 개발자는 HiddenMenu 컴포넌트로 아래와 같은 형식의 리스트 아이템을 전달해서 HiddenMenu 리스트를 원하는 대로 구성할 수 있습니다.
```jsx
[예]
const filterList = [
{ id: 0, title: '5km 이내', type: 'button', isConnectAlert: false, to: '' },
{ id: 1, title: '10km 이내', type: 'button', isConnectAlert: false, to: '' },
{ id: 2, title: '20km 이내', type: 'button', isConnectAlert: false, to: '' },
{ id: 3, title: '30km 이내', type: 'link', isConnectAlert: true, to: '/test' },
];
<HiddenMenu onClick={onClickHiddenMenuButtonHandler} itemList={filterList} />
[옵션 설명]
- id : key로 사용할 unique한 id
- title : 리스트에 들어갈 제목
- type : 아이템의 타입 (button, link 두 종류)
- isConnectAlert : button 타입일 때 Alert 컴포넌트와 연결할지 여부 (boolean값으로 전달해야 함) / link 타입인 경우에는 false 값으로 작성
- to : link 타입일 때 연결될 주소 / button 타입인 …
```

design: 리스트 아이템을 받아 HiddenMenu를 구성할 수 있도록 컴포넌트 확장 (#120)

---

src/components/common/TopNavBar/Styled.jsx

- 상단 topNavBar 스타일 z-index 값 오류로 컨텐츠와 겹치는 상황 발생. 팀장님이 제안해주신대로 z-index 값 100으로 수정하여 해결했습니다. 
close : #127

fix: TopNavBar style z-index 버그 수정 (#127)

---

src/components/common/TopNavBar/TopMainNav.jsx
src/components/common/TopNavBar/TopTitleNav.jsx

- 디자인 시안과 동일하게 구현하기 위해 TopNav를 커스텀했습니다.
- TopTitleNav에 `viewMoreBtn={false}`를 전달하면 더보기 버튼이 보이지 않습니다. (기본값 - 더보기 버튼 보임)
- TopMainNav에 `viewSearchBtn={false}`를 전달하면 검색 버튼이 보이지 않습니다. (기본값 - 검색 버튼 보임)
close : #126

design: TopNavBar 커스텀 (#126)

---

src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
src/components/common/Product/Product.jsx

- 판매 중인 상품과 ProductModal 연결
- Product가 onClick을 props로 전달 받음
- 내가 판매 중인 상품 클릭 시 ProductModal 출력
- 다른 사람이 판매 중인 상품 클릭 시 상품 url으로 이동
- 현재는 상품 리스트가 MultiItemCarousel 안에 있는데, 상품과 캐러셀의 독립성을 유지하기 위해 기능 개발시 분리할 필요가 있어 보입니다!
- 아래 부분은 테스트를 위해 넣어놓은 사항으로 기능 개발시 필요가 없다면 삭제하셔도 됩니다.
https://github.com/daengnyang-market/daengnyang-market-client/blob/0e85461af069211eb7c4617d3ff88eb8bf7ecb72/src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx#L12
- 내 판매 상품인 경우 모달 출력
- 다른 사람의 판매 상품인 경우 상품 url으로 이동(새 탭으로 이동)
- 현재는 테스트용으로 네이버 주소를 넣어놓았음
close : #136

design: 판매 중인 상품에 모달 연결 (#136)

---

src/components/common/TabMenu/TabMenu.jsx

- 디자인 시안과 동일하게 구현하기 위해 추가했습니다.
- 선택한 페이지에 따라 TabMenu 스타일이 변경됩니다.
- TabMenu에 props로 currentMenuId를 전달해주세요.
- id 종류
- 0 : 홈(생략시 기본값)
- 1 : 채팅
- 2 : 게시물 작성
- 3 : 집사생활
- 4 :  프로필
- 예) 채팅 페이지일 때
- `<TabMenu currentMenuId={1} />`
- 값을 생략했을때 (홈)
- currentMenuId={3}을 전달했을때 (집사생활)
close : #146

design: 선택한 페이지에 따라 TabMenu 스타일 변경 (#146)

---

src/components/common/TabMenu/TabMenu.jsx
src/pages/FollowListPage/FollowListPage.jsx
src/pages/communityPage/CommunityLayout.jsx
src/pages/profilePage/ProfilePage.jsx
src/routes/Router.jsx

- 페이지들을 연결하기 위해서 추가했습니다.
- 하단 TabMenu 클릭시 페이지와 TabMenu 스타일이 변경됨
- **주의! '/'는 현재 Splash 페이지로 연결되고 있으므로 '/home'으로 진입해야 확인이 가능합니다.**
- 채팅방 목록 페이지는 아직 작업중인 관계로 연결되지 않았습니다.
- 채팅방 목록 페이지 작업자분께서는 작업 후 아래의 과정을 통해 TabMenu와 연결해주세요!
1. routes/Router.jsx에 컴포넌트 추가
- 41번째 라인 `<Route path='/chat' element={<></>} />` 여기 element안에 다른 라우터들과 똑같이 컴포넌트 넣어주시면 됩니다!
2. 채팅방 목록 페이지 내 TabMenu 컴포넌트에 currentMenuId={1} 전달
- 예: `<TabMenu currentMenuId={1} />`
close : #158

feat: TabMenu에 페이지 연결 (#158)

---

.eslintrc.json

- switch-case문 사용시 ESLint 규칙에 어긋나 에러 발생
- 에러를 해결하기 위해 switch-case문 들여쓰기 규칙 추가
- switch-case 사용시 ESLint 에러가 발생하지 않아야 합니다.
- `SwitchCase: 1'의 의미
- `SwitchCase가 1로 설정된 상태에서는 2칸으로 case 절을 ​​들여씁니다.`
- 출처: [Cannot fix eslint rule on indenting case statements in switch statement](https://stackoverflow.com/questions/53055300/cannot-fix-eslint-rule-on-indenting-case-statements-in-switch-statement)
- 추가 사항
- ESLint가 적용된 상태에서 switch-case문을 사용할때는 default 구문이 꼭 있어야 합니다. default 구문을 작성하지 않으면 오류는 나지 않지만 경고가 계속 출력됩니다.
close : #156

chore: ESLint에 switch-case문 들여쓰기 규칙 추가 (#156)

---

src/components/common/TopNavBar/TopBasicNav.jsx
src/components/common/TopNavBar/TopMainNav.jsx
src/components/common/TopNavBar/TopSearchNav.jsx
src/components/common/TopNavBar/TopTitleNav.jsx
src/components/common/TopNavBar/TopUploadNav.jsx

- TopNav에 이동 기능을 추가하기 위해 수정했습니다.
- TopBasicNav, TopSearchNav, TopUploadNav, TopTitleNav에서 뒤로가기 버튼을 누르면 이전 페이지로 이동됩니다.
- TopMainNav에서 검색 버튼을 누르면 search 페이지로 이동됩니다.
close : #163

feat: TopNavBar 뒤로가기 및 search 페이지로 이동 기능 추가 (#163)

---

src/components/common/TopNavBar/TopBasicNav.jsx
src/components/common/modal/ProfileModal/ProfileModal.jsx
src/pages/profilePage/ProfilePage.jsx

- ProfilePage 내 헤더 더보기 버튼 클릭시 모달창이 뜨도록 추가했습니다.
- ProfilePage 내 헤더 더보기 버튼 클릭시 모달창이 뜹니다.
- 설정 및 개인정보 링크를 클릭하면 프로필 수정 페이지로 이동됩니다.
close : #135

feat: ProfilePage에 모달 연결 (#135)

---

src/components/common/TopNavBar/TopBasicNav.jsx
src/components/common/TopNavBar/TopTitleNav.jsx
src/pages/profilePage/ProfilePage.jsx
src/routes/Router.jsx

- 채팅방 페이지에서 더보기 버튼 클릭 시 ChatRoomModal을 띄우기 위해 변경
- 채팅방 페이지에서 더보기 버튼 클릭 시 채팅방 나가기 모달 출력
- 수정 사항
- 라우터에 ChatRoomPage 추가
- TopBasicNav는 ProfileModal으로만 연결되면 됨. 따라서 pageType 옵션 제거
- TopTitleNav에 더보기 버튼 클릭 시 ChatRoomModal 출력
close : #140

feat: 채팅방에 모달 연결 (#140)

---

src/components/common/Animation/Animation.jsx
src/pages/LoginMainPage/LoginMainPage.jsx
src/pages/SplashScreen/SplashScreen.jsx
src/routes/Router.jsx

- SplashPage에서 LoginMainPage로 자동 이동되는 기능을 추가했습니다.
- SplashPage에서 1.5초 후 LoginMainPage로 자동 이동
- LoginMainPage에 애니메이션을 추가하면서 냥그리 위치도 항상 가운데에 고정되도록 조절했습니다.
- 위치 수정 전
- 위치 수정 후
위치 수정 후
- SplashPage에서 LoginMainPage로 자동 이동 기능
- 같은 경로('/') 내에서 이동. isLoading의 상태를 이용해 구현
close : #170

feat: SplashPage에서 LoginMainPage로 자동 이동 기능 추가 (#170)

---

src/components/common/ProfileImage/ProfileImage.jsx

- scale-down한 이미지를 보여주기 위한 코드 추가를 위해서
- 이미지 size에 대응하여 이미지를 보여줄 수 있습니다.
- object-fit: scale-down; // IE 미지원
close : #174

style: scale-down한 이미지를 보여주기 위한 코드 추가 (#174)

---

src/pages/chatListPage/ChatList.jsx
src/pages/chatListPage/ChatListPage.jsx

- TabMenu 채팅 메뉴와 채팅 목록 페이지 연결
- TabMenu에서 채팅 메뉴를 누르면 채팅방 목록 페이지로 연결됩니다.
- ChatContents의 span 태그에 텍스트가 길어질 경우 말줄임이 되도록 `.ellipsis` 스타일도 적용했습니다. (.ellipsis는 global.css에 전역 스타일로 추가되어 있음)
- 드디어 모든 탭메뉴와 페이지 연결 완료! 🎉
close : #176

feat: TabMenu 채팅 메뉴와 채팅 목록 페이지 연결 (#176)

---

src/pages/ProfileSettingsPage/InputUserDescription.jsx
src/pages/ProfileSettingsPage/InputUserId.jsx
src/pages/ProfileSettingsPage/InputUserName.jsx
src/pages/ProfileSettingsPage/ProfileInfo.jsx

- 프로필 설정 페이지 기능 추가를 위해서
- 업로드 이미지 미리보기를 구현했습니다.
- 각 Input창을 분리했습니다. (수정 예정)
- 중복된 id검사를 dummyData를 활용해  시도했습니다.
- 특수문자 중 일부가 ( ` ), ( ^ ) 입력되어도 경고가 뜨지 않습니다. (수정 예정)
close : #173

feat: 프로필 설정 페이지 기능 추가 (#173)

---

src/context/AuthContext.jsx

- token 값이 localStorage에 저장되어 있는데도 null로 인식되는 버그를 수정하기 위해 변경
- token 값이 localStorage에 이미 저장되어 있다면, 저장된 token 값을 정상적으로 가져옵니다.
close : #211

fix: token 값이 localStorage에 저장되어 있는데도 null로 인식되는 버그 (#211)

---

src/components/common/modal/ProfileModal/ProfileModal.jsx

- 로그아웃 기능 구현
- 프로필 헤더 => 로그아웃 버튼 클릭 시 로그아웃 진행
- 로컬스토리지의 token이 삭제됩니다.
- context의 token 값이 null으로 변경됩니다.
- 루트 경로('`/`')로 이동됩니다.
close : #208

feat: 로그아웃 기능 구현 (#208)

---

src/components/common/modal/ProfileModal/ProfileModal.jsx
src/context/AuthContext.jsx
src/pages/EmailLoginPage/EmailLoginPage.jsx

- AuthContext에 로그인한 사용자의 accountname 저장
- 로그인시 로컬스토리지와 context에 accountname 값이 추가됩니다.
- 로그아웃시 로컬스토리지와 context에 accountname 값이 초기화됩니다.
close : #227

feat: AuthContext에 로그인한 사용자의 accountname 저장 (#227)

---

src/components/common/modal/ProfileModal/ProfileModal.jsx
src/context/AuthContext.jsx
src/pages/EmailLoginPage/EmailLoginPage.jsx
src/pages/FeedPage/FeedPage.jsx
src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx

- url 파라미터와 구분을 위해 AuthContext내 변수명을 수정했습니다.
- url 파라미터도 accountname, AuthContext에 사용자 아이디를 저장하는 변수명도 accountname으로 구분이 어려웠음
- `token => userToken`, `accountname => userAccountname`으로 변경
- AuthContext 안에 저장된 토큰 사용 시 `${userToken}`과 같이 사용하셔야 합니다.
- AuthContext 안에 저장된 accountname 사용 시 `${userAccountname}`과 같이 사용하셔야 합니다.
- develop 브랜치에 머지된 파일엔 위 수정 사항을 반영했습니다.
close : #229

style: url 파라미터와 구분을 위해 AuthContext내 변수명 수정 (#229)

---

src/components/common/userItem/Follow/Follow.jsx
src/components/common/userItem/UserAccountInfo/UserAccountInfo.jsx
src/pages/FollowListPage/EmptyFollowList.jsx
src/pages/FollowListPage/FollowListPage.jsx

- 팔로우 리스트 조회 및 팔로우/취소 기능을 구현하기 위해 추가했습니다.
- accountname 파라미터와 type 파라미터를 제대로 전달하면 팔로우 목록이 출력됩니다.
- accountname 파라미터와 type 파라미터 중 하나라도 정상적이지 않으면 404 페이지로 이동됩니다.
- 팔로잉, 팔로워 목록 조회가 가능합니다.
- 팔로우 버튼을 통해 팔로우/팔로우 취소가 가능합니다.
- 자신의 계정일때는 팔로우 버튼이 나타나지 않습니다.
- 사용자 리스트를 클릭하면 해당 사용자의 프로필로 이동합니다.
- 기대 결과 : 404 페이지로 이동
- 테스트 결과 : pass
- 기대 결과 : 404 페이지로 이동
- 테스트 결과 : pass
- 기대 결과 : 404 페이지로 이동
- 테스트 결과 : pass
- 기대 결과 : 팔로잉 목록 출력. 헤더 타이틀 Followings
- 테스트 결과 : pass
- 기대 결과 : '아직 팔로우한 사용자가 없어요.' 문구 출력. 헤더 타이틀 Followings
- 테스트 결과 : pass
- 기대 결과 : 팔로워 목록 출력. 헤더 타이틀 Followers
- 테스트 결과 : pass
- 기대 결과 : '아직 팔로워가 없어요.' 문구 출력. 헤더 타이틀 Followers
- 테스트 결과 : pass
- 기대 결과 : 팔로우 버튼을 누르면 팔로우, 취소 버튼을 누르면 팔로우 취소
- 테스트 결과 : pass
- **특이사항 : 버튼 클릭 시 버튼이 반짝거리는 현상이 있으나 Button 컴포넌트의 &:active 속성 때문인 것으로 확인. 기능에는 문제 없으니 이번 단계에선 …

feat: 팔로우 리스트 조회 및 팔로우/팔로우 취소 기능 구현 (#220)

---

src/components/common/Post/Post.jsx
src/pages/FeedPage/FeedPage.jsx
src/pages/PostDetailPage/PostDetailPage.jsx
src/pages/profilePage/ProfilePost/ProfilePost.jsx

- 서버에서 받아온 게시글 데이터를 뿌려주기 위해 Post 컴포넌트를 수정했습니다.
- 서버에서 받아온 게시글 데이터를 화면에 출력합니다.
- 날짜(createdAt)를 가공한 후 화면에 출력합니다.
- 프로필 부분을 누르면 사용자 프로필로 이동합니다.
- 컨텐츠 부분을 누르면 상세 게시글 페이지로 이동합니다.
- 댓글 버튼을 누르면 상세 게시글 페이지로 이동합니다.
- Post 컴포넌트를 쓰는 페이지 중 아직 작업중인 페이지(ProfilePage, PostDetailPage)에는 서버 응답과 유사한 형태의 테스트 데이터를 넣어놓았습니다.
- Post 컴포넌트에는 서버에게 응답받은 post 객체 자체를 넘겨주면 됩니다.
close : #246

feat: Post 컴포넌트에 서버 데이터 출력 (#246)

---

src/pages/ProfileModificationPage/ProfileModificationPage.jsx
src/pages/ProfileSettingsPage/InputAccountName.jsx
src/pages/ProfileSettingsPage/InputIntro.jsx
src/pages/ProfileSettingsPage/InputUserName.jsx
src/pages/ProfileSettingsPage/ProfileInfo.jsx
src/pages/ProfileSettingsPage/ProfileSettingsPage.jsx

- 프로필 정보를 불러오기 위한 통신 기능 추가 및 props 추가
- 페이지 이동 기능 추가
- image 미리보기 기능 추가
- 버튼 상태관리 추가
-  프로필 수정을 할 수 있습니다.
- 버그가 수정되어 업데이트될 예정입니다. 
- 현재 아래와 같이 계정 ID의 입력값을 바꿨다가 다시 기존 계정 ID로 돌아가면 사용 중인 ID로 인지하는 버그가 있습니다.
- #261
- 추가 버그 발견 시 제보 부탁드립니다!
close : #253

feat: 프로필 수정 페이지 기능 구현 (#253)

---

src/pages/ProfileSettingsPage/ProfileSettingsPage.jsx

- #266 
- 위 현상을 수정하기 위해서 작업했습니다.
- 버그가 개선되었습니다.
- 없습니다.
close : #266

fix: 회원가입 시 이미지 미적용에 따른 기본 프로필 이미지로 대체되는 현상 수정 (#266)

---

src/pages/profilePage/ProfileHeader/ProfileHeader.jsx

- 내 프로필 페이지에서 follower/following 버튼 클릭하면 notFound가 뜨는 현상을 해결했습니다. 승연님이 알려주신 방법대로 해결!
- 눌러도 팔로우/팔로잉 리스트 잘 나옵니다
_- 똑같은 코드에 follower/following 만 바뀌는거라 하나로 묶고 전달해주는 방법을 쓰고 싶었는데, 뭔가 문법오류(?)가 있는건지 잘 전달이 안돼서 그냥 두개로 나눴습니다. ㅠㅠ 이 부분 리팩토링시 깔끔하게 수정하려고 합니다!_
=> 이 부분 알려주셔서 개선했습니다. 속시원...
close : #265

fix: 프로필페이지에서 follower 진입시 notFound뜨는 에러 해결 (#265)

---

src/components/common/ProfileImage/ProfileImage.jsx

- 프로필 이미지가 꽉 차지 않는 현상 해결
- 프로필 이미지가 꽉 차게 보여집니다
close : #276

fix: 프로필 이미지가 꽉 차지 않는 현상 해결을 위해 object-fit: cover로 변경 (#276)

---

src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
src/pages/profilePage/ProfilePost/ProfilePost.jsx
src/pages/profilePage/ProfileProduct/ProfileProduct.jsx

- 프로필페이지에서 게시물이나 판매중인 상품이 없을때의 화면을 재구성하였고, 뜨지 않는 현상을 수정했습니다
close : #282

style :프로필페이지 게시물/상품 없을때의 화면 수정 (#282)

---

src/components/common/modal/Alert.jsx

- 기존 ) 트리거 버튼이 두 개인 경우만 사용 가능 (취소/수정, 취소/삭제, 취소/신고 등)
- 수정 후 ) 트리거 버튼이 한 개인 경우도 사용 가능 (확인 등)
- 트리거 버튼이 한 개인 경우에도 Alert 컴포넌트를 사용할 수 있습니다.
- 트리거 버튼이 한 개인 경우에는 props로 closeAlert을 전달하지 않으면 됩니다.
- 트리거 버튼이 한개인 경우 적용 예시 )
```jsx
<Alert
summary={is신고성공여부 ? '게시글 신고 완료 알림창' : '게시글 신고 실패 알림창'}
title={is신고성공여부 ? '게시글이 신고되었습니다.' : '게시글 신고에 실패하였습니다.'}
trigger={'확인'}
tiggerFunc={clearReportPost}
/>
```
- 기존 ) 트리거 버튼이 두개인 경우에만 사용 가능했음
- 수정 후 ) 위와 같은 경우도 사용 가능
close : #298

feat: props로 closeAlert을 전달받지 않은 경우 closeAlert 버튼이 출력되지 않도록 수정 (#298)

---

src/hooks/useCurrentLocation.jsx
src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
src/pages/communityPage/communityHospitalPage/CommunityHospitalMainPage/CommunityHospitaMainlPage.jsx

- react-router-dom Hook과 custom Hook의 이름이 `useLocation`으로 동일하여 에러 발생
- useLocation 훅 사용시 에러가 발생하지 않습니다
close : #302

fix: useLocation 커스텀 훅을 useCurrentLocation으로 변경 (#302)

---

src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx

- 채팅방 이동하기/ 공유하기 기능을 추가했습니다. 
- 공유하기 버튼 누르면 카카오톡으로 공유가 가능합니다.
- 현재 localhost 3000번으로 주소는 임시 저장해놓은 상태입니다!
- API 불러오고나서 프로필 페이지가 급격히 느려진 것 같습니다....리팩토링할때 고려해봐야할 것 같습니다 ㅠㅠ
close : #294

feat: 프로필페이지 채팅 이동 및 카카오톡 공유하기 기능 추가 (#294)

---

src/components/common/Post/Post.jsx

- 게시물의 이미지가 존재하지 않을때도, 빈 이미지 파일이 렌더가 되어서 변경하였습니다.
- 게시물의 이미지가 존재할 경우에만, 렌더를 하도록 설정하였습니다.
- 확인부탁드려요~!
close : #338

fix: 게시물 이미지 파일이 존재하지 않을때도 빈 이미지 파일이 렌더되는 현상 수정 (#338)

---

src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
src/pages/profilePage/ProfilePage.jsx
src/pages/profilePage/ProfilePost/ProfilePost.jsx
src/pages/profilePage/ProfileProduct/ProfileProduct.jsx

- 프로필페이지, 상품, 게시글 컴포넌트에 로딩되는 동안 사용자에게 로딩 화면을 보여줄 수 있게 추가했습니다
- 프로필 페이지, 상품 , 포스트 각각 3개에 로딩 컴포넌트를 추가했더니 너무많아서 징그러워 보이기도 합니다. 피드백 부탁드립니다 ㅠㅠ
close : #342

refactor: 프로필페이지,상품,게시글  로딩컴포넌트 추가 (#342)

---

src/components/common/Post/Post.jsx
src/pages/PostDetailPage/PostComment.jsx

- 댓글버튼 클릭시 `/data/data.id 로 구현이 되어있어서 수정했습니다
- 이제 드디어 내 게시글의 댓글들을 볼 수 있습니다
- 상세페이지에 현재 댓글 프로필 이미지가 네모 모양으로 나오는데, 해당 부분도 추가로 수정했습니다
close : #350

fix: Post 댓글버튼 클릭시 상세페이지로 이동하게 수정 (#350)

---

src/components/common/Button/Button.jsx
src/components/common/userItem/Follow/Follow.jsx

- 팔로우 페이지에서 버튼이 깜빡이는 현상을 수정하기 위해 active 스타일 온/오프를 위해 isActive 옵션을 추가했습니다.
- 기본값을 true로 설정해둬서 이미 만들어진 버튼은 수정할 필요가 없습니다.
- isActive=false 옵션을 주면 active 효과가 적용되지 않습니다.
- 팔로우 페이지에서 버튼 깜빡이는 현상이 사라집니다.
- [Styled Components: props for hover](https://stackoverflow.com/questions/47635991/styled-components-props-for-hover)를 참고해서 수정했습니다.
close : #358

design: 버튼 컴포넌트에 isActive 옵션 추가 (#358)

---

src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx

- 이미지 리사이징을 위한 ProductRegistrationPage.jsx 리팩토링을 진행했습니다.
- 이미지 스타일 속성을 기존 프로필 이미지 속성과 동일하게 ``object-fit: scale-down;`` 에서 ``object-fit: cover;`` 로 변경 했습니다.
- 이미지 리사이징 코드가 추가 되어 비교적 용량이 큰 이미지도 업로드가 가능합니다.
- 이미지가 종횡비를 유지하면서 정의된 너비와 높이를 가득 채울때까지 확대됩니다.
- 아래와 같이 옵션 값을 부여할 수 있습니다.
```jsx
maxSizeMB: number,
maxWidthOrHeight: number,
```
- 머지 이후에 평소에 업로드가 잘되지 않았던 파일로 확인해 보시고 피드백 부탁드립니다!
> ![image](https://user-images.githubusercontent.com/112460383/209811256-f06e65f3-8aab-40ef-98f9-2dc20b194df9.png)
**위와 같이 102400B (100KB)로 제한이 되어있으므로, 업로드가 되지 않습니다.**
> ``리사이징 이전 이미지 파일 크기`` 
> ``리사이징 이후 이미지 파일 크기`` 
**기존 이미지 크기의 1% 수준으로 크기가 줄어들었습니다.**
close : #352

refactor: 이미지 리사이징을 위한 코드 추가 및 이미지 스타일 속성 변경을 위한 코드 수정 (#352)

---

src/pages/ProductRegistrationPage/ItemNameInput.jsx

- 명세에 따라 2-15자 이내로 상품명을 입력해야 합니다. 하지만 현재 제가 작성한 코드는 2-10자 이내로 입력해야 버튼이 활성화 되고, 11~15자를 입력하면 버튼 활성화가 풀리는 상황이었기 때문에 수정했습니다.
- 올바른 길이의 상품명을 입력하고 기능이 정상 작동합니다.
close : #363

fix: 상품명 길이 제한 수정 (#363)

---

src/pages/ProductModificationPage/ProductModificationPage.jsx
src/pages/ProductRegistrationPage/ItemLinkInput.jsx
src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx

- 그냥 타이핑해서 올바른 주소를 입력하면 버튼이 정상적으로 활성화되지만, 주소를 복사해서 입력하면 바로 활성화되지 않고 해당 인풋창에 입력 값의 변화를 한 번 더 줘야 버튼이 활성화되었던 부분을 수정했습니다.
- 판매 링크 입력창의 정상적인 작동을 기대할 수 있습니다.
- 이제 복붙해도 정상 작동합니다.
- 추후 리팩토링이 진행될 수 있습니다.
close : #365

fix: 판매 링크 입력 시 주소를 복사해서 넣으면 생기는 버그 수정 (#365)

---

src/components/layout/ContentsLayout/ContentsLayout.jsx
src/pages/profilePage/ProfilePage.jsx
src/pages/profilePage/ProfilePost/ProfilePost.jsx

- 프로필페이지 피드 게시글이 없을 때 세로로 긴 화면에서 공간이 남아 보이는 현상 해결을 위해 추가했습니다.
- 세로로 긴 디바이스에서도 피드 게시글이 없을 때 화면에 꽉 차서 보입니다.
- 게시글이 없을 때만 ContentLayout에 isFill=true를 전달합니다.
- ContentLayout에 isFill=true을 전달하면 ContentLayout이 100vh-110px만큼의 공간을 차지합니다.
- 기본값은 isFill=false입니다.
close : #367

fix: 프로필페이지 피드 게시글이 없을 때 세로로 긴 화면에서 공간이 남아 보이는 현상 해결 (#367)

---

src/pages/FollowListPage/FollowListPage.jsx

- 팔로워, 팔로잉 리스트가 최대 10개까지만 보이는 현상 해결
- 팔로워, 팔로잉 리스트를 모두 확인할 수 있습니다.
- limit는 고정하고 skip을 추가하는 방식으로 우회하여 무한스크롤을 구현해보려고 했으나 이 방법으로 API 테스트 시에도 순서가 뒤죽박죽 되는 것으로 확인되었습니다.
- 결국 처음 말했던대로 전체 리스트를 가져오는 방식으로 임시 조치를 취했습니다.
close : #361

fix: 팔로워, 팔로잉 리스트가 최대 10개까지만 보이는 현상 (#361)

---

src/pages/profilePage/ProfilePost/ProfilePost.jsx
src/pages/profilePage/ProfileProduct/ProfileProduct.jsx

- 앨범형 리스트에서 이미지 클릭시 포스트 디테일로 이동하지 않는 현상이 있어 Link 태그를 넣었습니다
- 이제 클릭하면 게시글 상세를 볼 수 있습니다
close : #374

fix: 앨범형 게시글 클릭 시 포스트 디테일로 이동하게 수정 (#374)

---

src/pages/profilePage/ProfileHeader/ProfileHeader.jsx

- 소개글이 길 경우 양쪽에 여백 없이 붙어버리는 현상이 발생해서 padding 값 추가했습니다
close : #378

style: 프로필 소개글 양쪽 여백 스타일 추가 (#378)

---

package-lock.json
package.json
src/components/common/Post/Post.jsx
src/pages/FeedPage/FeedPage.jsx

- 버그리포트의 '피드 게시물이 최대 10개까지만 보이는 현상' 을 라이브러리를 설치하여 스크롤을 내리는 방법으로 해결하고자 했습니다.
- 피드게시물을 무한으로 내려볼 수 있습니다
-  머지 후 package.json에  "react-intersection-observer": "^9.4.1", 가 추가되었는지 확인 부탁드립니다
- `npm i ` 명령어로 모듈 설치 부탁드립니다 
- 참고자료 : https://devkkiri.com/post/927ae150-7627-4e25-b29f-2d0293b82332
- 에러가 발생하거나 버그를 보시면 바로 말씀 부탁드립니다. 
- 이전에 useEffect 이슈가 있어서 확인용 console.log()을 넣고 일단 주석처리 해둔 상태입니다. 리팩토링때 문제 없다면 지우겠습니다
close : #354

feat: react-intersection-observer 라이브러리로 피드 페이지 무한스크롤 기능 추가 (#354)

---

src/pages/communityPage/CommunityMainPage/CommunityMainPage.jsx
src/pages/communityPage/CommunityMainPage/PopularPosts.jsx

- 커뮤니티 메인 페이지에서 게시물이 최대 20개까지만 보이는 문제 해결을 위해 무한 스크롤 기능 추가
- API의 한계로 인해 문구를 **실시간 인기글**이 아니라 **오늘의 추천글**로 변경
- 커뮤니티 메인 페이지에서 피드 게시물 + 내 게시물을 **일부 정렬된 형태**로 볼 수 있습니다.
- 기존 : 게시물 20개를 미리 가져온 후 => 가져온 게시물 안에서 하트수, 댓글수, 최신순으로 정렬함 (즉 인기글처럼 보이게 가공 가능했음)
- 무한스크롤 구현 후 : 스크롤을 한 번 내릴때마다 게시물을 최대 20개씩 가져옴 => 그러다보니 모든 게시물을 하트수, 댓글수, 최신순으로 정렬해서 보여주는게 불가능. (모든 게시물을 하트순 정렬 / 댓글순 정렬해서 반환해주는 API는 존재하지 않음)
- 따라서 스크롤 한 번 내릴때 추가되는 게시물 안에서만 정렬했고, 문구를 **오늘의 추천글**로 바꿈
```
예)
최초 스크롤시 : 가져온 게시물 안에서만 하트+댓글이 많은 순서대로 정렬
두번째 스크롤시 : 새로 가져온 게시물 안에서만 하트+댓글이 많은 순서대로 정렬
반복
...
```
close : #369

feat: 커뮤니티 메인 페이지 무한 스크롤 구현 및 추천글 정렬 기준 변경 (#369, #370)

---

src/pages/profilePage/ProfilePage.jsx

- 피드 페이지 게시물이 없을 때 공간이 남아 보이는 현상 해결을 위해 누락된 코드 추가
- 게시물이 없어도 화면에 꽉 차보입니다.
close : #387

fix: 피드 페이지 코드 누락으로 게시물이 없을 때 공간이 남아 보이는 현상 (#387)

---

src/components/layout/ContentsLayout/ContentsLayout.jsx
src/pages/profilePage/ProfilePage.jsx
src/pages/profilePage/ProfilePost/ProfilePost.jsx
src/pages/profilePage/ProfileProduct/ProfileProduct.jsx

- 프로필 페이지에서 게시물이 없고 상품이 있는 경우 ProfilePost 영역이 작아지는 현상 해결을 위함
- 프로필 페이지에서 게시물이 없고 상품이 있는 경우 영역이 작아지는 현상이 해결됨
- empty게시물, empty 상품 상태에 따라 레이아웃을 다르게 잡는 emptyProfileState 추가. 기본값 null
- 게시물X 상품X : 테스트 완료
- 게시물O 상품X : 테스트 완료
- 게시물X 상품O : 테스트 완료
close : #390

bug: 프로필 페이지에서 게시물이 없고 상품이 있는 경우 ProfilePost 영역이 작아지는 현상 (#390)

---

src/components/common/Button/Button.jsx
src/components/common/TopNavBar/TopUploadNav.jsx
src/pages/ProfileModificationPage/ProfileModificationPage.jsx
src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx

-  프로필정보 변경시 바로 업데이트가 되지 않고, 새로고침을 해야 업데이트가 되는 현상을 수정했습니다.
- 이제 프로필 변경하면 바로 반영됩니다.
- Button에 `type` props가 생성되었습니다.
https://user-images.githubusercontent.com/96304623/209989752-41d0b4a3-5541-4ea1-9eac-724e54317ca2.mov
close : #398

fix: 프로필 수정시 바로 업데이트 되지 않는 버그 해결 (#398)

---

src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx

- 이전에는 기능 구현에만 초점을 맞추어 디자인이 다소 밋밋했습니다. 리팩토링 단계에서 이미지나 소개글을 추가해보았습니다.
- 자세한 소개글과 귀여운 냥그리의 이미지를 공유하여 사용자들에게 호기심을 유발할 수 있고, 이는 사용자수 증가에 크게 기여할 수 있습니다. 
`기존이미지`
`업데이트 후 이미지 `
close : #399

feat: 카카오톡 프로필 공유시 이미지 추가 및 소개글 수정 (#399)

---

src/components/carousel/MultiItemCarousel/multiItemCarousel.css

- 판매하는 상품이 1-2개일 경우 하단의 여백이 너무 길어서 허전해보였습니다. 
- 높이값을 조금 조정했습니다
- (사실 캐러셀 버튼을 한개라도 띄우고 싶어서 이것저것 조정 해보았으나 잘 되지 않았습니다. 추후 가능하다면 수정해보겠습니다 ㅠㅠ)
close : #391

style: ProfileProduct 캐러셀 높이값 조정 (#391)

---

src/components/common/TopNavBar/TopTitleNav.jsx
src/hooks/useCurrentLocation.jsx
src/pages/communityPage/CommunityHospitalPage/CommunityHospitalMainPage/CommunityHospitalMainPage.jsx
src/pages/communityPage/CommunityHospitalPage/CommunityHospitalMainPage/FilterMenu.jsx
src/pages/communityPage/CommunityHospitalPage/CommunityHospitalMainPage/HospitalList.jsx
src/pages/communityPage/CommunityLayout.jsx
src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx

- 동물병원 근처 동물병원이 최대 15개만 보이는 버그를 수정했습니다.
- 동물병원 메인 페이지 -> 상세 페이지 접속 -> 상세 페이지에서 뒤로가기 -> 기존 거리 필터를 유지하는 기능을 추가했습니다.
- 기타 사소한 부분을 수정했습니다.
- 기존에는 거리 당 동물병원을 최대 45개씩 가져왔으나 최대 30개만 가져오도록 수정
- 거리 필터 축소
- 기존 : 1km, 5km, 10km, 20km
- 수정 : 1km, 5km, 10km
- 카카오 API를 이용했을 때 한 거리당 최대 45개까지만 가져올 수 있음. 무한정으로 가져올 수 있는게 아니다보니 10km와 20km의 데이터가 동일한 경우가 많았음. 따라서 20km 필터를 삭제함.
- `더보기 버튼`을 클릭해서 동물병원을 최대 30개까지 확인할 수 있습니다.
- 동물병원 메인 페이지 -> 상세 페이지 접속 -> 상세 페이지에서 뒤로가기 -> 기존 거리 필터가 유지됩니다.
- 뒤로가기를 하지 않은 경우에는 `1km` 기준으로 보여집니다.
- 상세 페이지에서 뒤로가기 했을 때 거리 필터 뿐만 아니라 보고 있던 위치까지 유지하는 기능을 추가해보려 했으나 아직 저의 실력 부족으로 완성하지 못했습니다. 발견된 버그를 모두 수정한 후 다시 도전해보겠습니다..🥺
- 데이터를 추가로 가져올 때, 무한 스크롤으로 구현할지 더보기 버튼으로 구현할지 고민했는데 더보기 버튼으로 구현했습니다.
- 동물병원 리스트는 가져올 때부터 현재 위치에서 가까운 순으로 정렬되어 서버에서 넘어옵니다.
- 사용자 입장에서 생각해봤을 때, 가까운 동물병원보다 먼 동물병원을 궁금해하는 경우는 …

fix/feat: 동물병원 근처 동물병원이 최대 15개만 보이는 버그 수정 및 필터 유지 기능 추가 (#386, #404)

---

src/pages/ProfileModificationPage/ProfileModificationPage.jsx
src/pages/profilePage/ProfilePage.jsx

- 프로필 계정 ID 수정 시 프로필 페이지가 먹통이 되는 오류를 개선하기 위해 수정했습니다.
- 프로필 계정 ID 수정 후, 변경된 계정 ID로 원하는 페이지를  정상적으로 사용 가능합니다.
- 좀 더 효율적인 방법을 고민하다 실패하여, 우선 버그가 수정되어야 함을 우선으로 하여 작업했습니다.
- 이후 효율적인 렌더링을 위해 리팩토링이 진행될 수 있습니다.
close : #383

fix: 프로필 계정 ID 수정 시 프로필 페이지 오류 현상 개선 (#383)

---

src/components/common/userItem/UserAccountInfo/UserAccountInfo.jsx

- UserAccountInfo 내부 내용이 길어질 경우 넘치는 현상을 해결하기 위해 수정했습니다.
- 사용자명, 아이디 max-width를 20rem으로 설정했습니다.
- 20rem을 넘어갈 경우 말줄임 스타일을 적용했습니다.
- 사용자명, 아이디가 길어도 UserAccountInfo를 넘어가지 않습니다.
- 사용자명, 아이디를 화면에 보여주는 페이지를 맡으신 분들은(프로필 페이지 등) 각자 맡으신 페이지에서`abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz` 계정 확인 시 오류가 없는지 한번씩 체크부탁드립니다.
- 수정 전
- 수정 후
close : #416

fix: UserAccountInfo 내부 내용이 길어질 경우 넘치는 현상 (#416)

---

src/components/common/Post/Post.jsx

- 게시물에서 이미지 짤리는 현상 및 댓글과의 간격이 거슬려서 수정했습니다.
- 사진을 잘리지 않고  크게 볼 수 있습니다
close : #423

fix: 캐러셀 높이값 수정 및 하단과의 간격 추가 (#423)

---

src/pages/ProfileSettingsPage/InputAccountName.jsx
src/pages/ProfileSettingsPage/ProfileInfo.jsx

- 아래와 같은 변경이 필요해서 수정하였습니다.
- 프로필 설정 페이지 내 불필요한 코드를 제거
- #250 에서 언급한 계정 ID 정규식 업데이트 (`` ` ``, ``^``, ``공백 입력`` 대응) 
- 원할한 소개작성을 위한 소개 input 창 입력 제한 100글자로 증가
- 정규식이 업데이트되어 보다 정확한 유효성 검사가 가능해집니다.
- 이전보다 많은 양을 소개란에 작성할 수 있습니다.
- 없습니다.
close : #426

refactor: 프로필 소개, 계정 ID에 대한 프로필 세팅 페이지 리팩토링 (#426)

---

src/components/common/Post/Post.jsx

- 포스트의 컨텐츠가 길 경우 화면밖으로 나가버리는 현상을 방지하기 위해 
` word-break: break-word` 속성 부여했습니다.
- 이제 컨텐츠가 길어도 화면 밖으로 삐져나가지 않습니다.
close : #424

fix: 게시물 글이 길 경우 화면 밖으로 빠져나가는 현상 word-break 속성 추가로 해결 (#424)

---

src/pages/FeedPage/FeedPage.jsx
src/pages/profilePage/ProfilePost/ProfilePost.jsx

-  무한스크롤 기능을 추가했더니 가장 마지막의 게시글이 보이지 않아 수정했습니다. 
- 마지막 게시글까지 잘 보입니다.
close : #

fix: 무한스크롤 기능 추가시 가장 마지막 게시글 보이지 않는 현상 수정 (#429)

---

src/pages/profilePage/ProfilePage.jsx

- 프로필 주소 변경시 프로필 포스트들이 재렌더링 되지 않는 현상이 발생하여 해결했습니다.
* `location.key()`사용
=> 위치를 나타내는 고유 문자열. useLocation으로 받아오는 값이 갱신되면 새로 컴포넌트를 불러오는 코드라고 합니다. 
현재 post 부분이 현재 갱신되고 있지 않아서 profilePost에 key값으로 `location.key()`를 부여해주었습니다. 
( 승연님의 도움을 받아 검색하는 방법도 새로 변경해보았습니다!)
<a href='https://stackoverflow.com/questions/46820682/how-do-i-reload-a-page-with-react-router'>참고한 사이트</a>
이전에는 단순히 useEffect의 의존성배열에 `location.pathname`이나 useParams로 가져온`accountname` 등을 사용해서, 
주소값이 변경될 경우 useEffect의 첫번째 요소가 실행될거라고 생각해서 시도해봤습니다. 
``` useEffect(() => {
console.log(location.pathname);
getPost()
}, [location.pathname]);
```
location의 변화는 감지하지만 재렌더링을 발생시키지는 않았습니다. ㅠㅠ
원범멘토님께 코드리뷰를 받았는데, 몇가지 피드백을 주셨습니다.
```
1. 리액트의 리렌더링은 컴포넌트의 props 또는 state가 바뀌었을때 발생한다. 하지만 이 코드에서는 profile 정보가 바뀌어도 post의 상태가 바뀌는 부분이 없는 것 같다.
2. 게시글 리스트를 언제 …
```

fix: 프로필 주소 변경시 프로필 포스트들이 재렌더링 되지 않는 현상 해결 (#421)

---

src/pages/PostUploadPage/ImageUploadButton.jsx

- 게시물 업로드 및 수정시, 이미지 3장이상 업로드가 불가능하여야 하기 때문이다.
- 3장 이상 업로드를 수행할 시, alert 창이 뜬다.
- 확인부탁드려요~!
close : #434

fix: 게시물 업로드 및 수정시, 이미지 3장이상 업로드 불가하도록 수정 (#434)

---

src/pages/ChatListPage/ChatListPage.jsx

- ChatListPage key 중복 경고 해결
- ChatListPage key 중복 경고가 해결됩니다.
- ChatList를 감싸는 button에 key 설정
- else 조건문 안에서도 key 설정. 다만 이때는 빈 태그(Fragment)이므로 Fragment에 key 설정
- 수정 전 콘솔
- 수정 후 콘솔
close : #442

fix: ChatListPage key 중복 경고 해결 (#442)

---

src/pages/ProfilePage/ProfilePost/ProfilePost.jsx

- ProfilePost 앨범뷰 키 중복 경고 해결을 위해 수정했습니다.
- ProfilePost 앨범뷰 키 중복 경고가 해결됩니다.
- 반복 요소의 가장 상위 태그가 아니라 내부 태그에 key가 적용되어 있어서 경고 발생 (즉 반복되는 모든 요소의 상위 태그에는 key가 누락되어 있어서)
- 그래서 가장 상위 태그에 key 적용
close : #451

fix: ProfilePost 앨범뷰 키 중복 경고 해결 (#451)
