- src/components/common/.gitkeep
- src/hooks/.gitkeep
- src/pages/.gitkeep
- 프로젝트 초기 세팅 시 빈 폴더라 누락된 디렉토리들을 추가했습니다.
- components/common, hooks, pages 디렉토리가 생성됩니다.
close : #7
> add: components, hooks, pages 디렉토리 추가 (#7)

- src/styles/GlobalStyle.jsx
- src/styles/global.css
- 편의를 위해 변경하였습니다.
- 
- 변경하였습니다.
close : #15
> design: 전역 스타일 수정 및 추가 (#15)

- src/components/common/Button/Button.jsx
- 버튼을 사이즈별로 사용할 수 있게끔 스타일하였습니다.
- 사이즈별 필요한 버튼을 사용할 수 있습니다.
- 확인해주시면 감사하겠습니다.
close : #11
> design: 공통UI 파트4 버튼 화면개발 (#11)

- src/components/common/Post/Post.jsx
- src/components/common/Product/Product.jsx
- components/common 디렉토리 안에 공통UI 파트1 구현하여 추가했습니다.
- Post : 홈 화면의 포스트
- Product : 판매중인 상품
close : #12
> design: 공통UI 파트1 화면개발 (#12)

- src/components/common/Alert/Alert.jsx
- src/components/common/Animation/Animation.jsx
- src/components/common/HiddenMenu/HiddenMenu.jsx
- src/components/common/Input/Input.jsx
- src/components/common/ProfileImage/ProfileImage.jsx
- src/components/common/userItem/Follow/Follow.jsx
- src/components/common/userItem/Search/Search.jsx
- src/components/common/userItem/UserAccountInfo/UserAccountInfo.jsx
- components/common 디렉토리 안에 공통UI 파트3 요소들을 구현하여 추가하였습니다.
- Alert : 경고 모달 창
- Animation : 공통 애니메이션
- HiddenMenu : 히든 메뉴 리스트
- Input : 인풋창
- ProfileImage : 사용자 프로필 이미지
- userItem/Follow : 팔로우한 사용자 아이템
- userItem/Search : 사용자 검색 결과 아이템
- userItem/UserAccountInfo : 사용자 계정 정보(Follow, Search 컴포넌트에서 공통으로 사용됨)
1. 아래 5가지 UI를 불러와서 사용할 수 있습니다.
2. 프로필 이미지를 불러와서 사용할 수 있습니다.
3. 애니메이션을 불러와서 사용할 수 있습니다.
- 협업자의 편의를 위해 사용법이 필요한 컴포넌트에는 주석으로 사용법을 달아놓았습니다.
- HiddenMenu.jsx
https://github.com/daengnyang-market/daengnyang-market-client/blob/677d8d9a34be35002a25d1952ed8f3dca8efd615/src/components/common/HiddenMenu/HiddenMenu.jsx#L7-L10
- Input.jsx
https://github.com/daengnyang-market/daengnyang-market-client/blob/677d8d9a34be35002a25d1952ed8f3dca8efd615/src/components/common/Input/Input.jsx#L4-L8
- …
> design: 공통UI 파트3 화면개발 (#10)

- src/components/common/userItem/Follow/Follow.jsx
- Button 스타일을 적용했습니다.
- Follow 컴포넌트의 버튼에 Button size='S' 스타일이 적용됩니다.
close : #24
> design: Follow 컴포넌트에 Button 스타일 적용 (#24)

- src/components/common/Comment/Comment.jsx
- src/components/common/TopNavBar/TopUploadNav.jsx
- 팀원들이 짜주신 Button과 ProfileImg 컴포넌트를 추가했습니다.
close : #21
> design: 공통UI 파트2 화면개발 버튼 및 프로필 이미지 컴포넌트 추가 (#21)

- src/components/common/Post/Post.jsx
- 팀원분이 작업하신 ProfileImage 컴포넌트를 추가했습니다
close : #26
> design: 공통UI 파트1 화면개발 ProfileImage 컴포넌트 추가 (#26)

- src/components/common/Input/Input.jsx
- 부모요소에 영향을 받도록 하기 위해서 변경하였다.
- 부모요소의 크기에 비례하여, Input 요소들의 크기가 달라질 것이다.
- 확인부탁드려요~!
close : #32
> design: Input.jsx 속 InputWrapper 스타일 수정 (#32)

- src/components/common/Product/Product.jsx
- Product 컴포넌트의 오타를 수정했습니다.
close : #37
> style: Product 컴포넌트 오타 수정 (#37)

- src/components/common/Button/Button.jsx
- 전에는 padding 값을 적용하여, 버튼안에 글씨가 제한되었다.
- 이번 변경으로 조금 더 자유로워 졌을 것이다.
- 확인부탁드려용~!
close : #36
> design: 버튼 사이즈별 width를 고정값으로 수정 (#36)

- src/components/common/Button/Button.jsx
- 버튼사이즈가 다르게 기입되어 있었습니다.
- 제대로 된 크기로 들어갔습니다.
- 확인부탁드려요!
close : #41
> design: 버튼 사이즈가 L 일 때의 스타일 변경 (#41)

- src/pages/SplashScreen/SplashScreen.jsx
- 시작화면 퍼블리싱 완료했습니다.
close : #29
> design: 시작 화면 퍼블리싱 완료 (#29)

- src/pages/EmailLoginPage/EmailLoginPage.jsx
- src/pages/LoginMainPage/LoginMainPage.jsx
- 이메일 로그인 화면을 구현했습니다.
- EmailLoginPage/EmailLoginPage.jsx 파일이 추가됩니다.
- EmailLoginPage.jsx 파일을 호출하면 이메일 로그인 화면이 나타납니다.
close : #30
> design: 이메일 로그인 화면 퍼블리싱 (#30)

- src/components/common/Input/Input.jsx
- 피그마시안과 다른 스타일이라 변경하였습니다.
- InputText 의 스타일 속성에, placeholder 색상을 지정해 주어 피그마 시안에 맞게 변경되었다.
- 확인부탁드려요~
close : #48
> design: Input.jsx 스타일 추가 (#48)

- src/components/common/Button/Button.jsx
- src/components/common/Input/Input.jsx
- 버튼속성으로 disabled 를 추가 함으로써, true 값일 경우에는 버튼을 막았다. 또한 true 일 경우와 false 일 경우 스타일을 지정해 두었다. 이를 통해, 유효성검사 통과 유무에 따라 다르게 스타일을 나타내고 싶었기 때문이다.
- 유효성 검사를 통과못한다면, 버튼이 작동이 되지않으며 그에 맞는 스타일로 나타나 화면을 구성할 것이다.
- 확인 부탁드려요~!
close : #49
> design: Button.jsx 속성 추가 및 속성에 맞는 스타일 지정 (#49)

- src/pages/JoinMembershipPage/JoinMembershipPage.jsx
- 전체적인 회원가입 메인화면을 구성하기 위하여 디자인했습니다.
- 회원가입 메인화면이 피그마 시안에 맞게 렌더링 될것입니다.
- 확인부탁드려요~!
close : #27
> design: 회원가입 메인화면 구성 (#27)

- src/components/common/Button/Button.jsx
- L,MS 사이즈의 버튼 ( 활성화 될때와 안될때 ) 스타일의 우선순위 변경을 하기 위해서 변경하였습니다.
- 적절한 우선순위를 통하여, 피그마 시안 과 동일하게 동작할것 입니다.
- 확인부탁드려용~!
close : #57
> design: Button.jsx 파일 스타일 변경 (#57)

- src/components/common/Button/Button.jsx
- 버튼의 배경색, 텍스트색, 보더색 커스텀을 위해 변경했습니다.
- 버튼에 onClick 이벤트를 적용하기 위해 변경했습니다.
- 배경색, 텍스트색, 보더색 커스텀이 가능합니다.
- onClickHandler 함수 전달이 가능합니다.
https://github.com/daengnyang-market/daengnyang-market-client/blob/defa9cc9add7619194137cb5041a71762d82e99e/src/components/common/Button/Button.jsx#L4-L12
- 원래 설정되어 있던 값은 기본값으로 설정해놨습니다. 따라서 사용중이신 버튼 스타일을 따로 수정하실 필요는 없습니다.
close : #72
> style: Button 커스텀을 위한 props 및 클릭핸들러 추가 (#72)

- src/components/common/TopNavBar/Styled.jsx
- src/components/common/TopNavBar/TopSearchNav.jsx
- src/pages/SearchPage/SearchPage.jsx
- Search 화면을 퍼블리싱 한다.
- Search 화면에 맞게, Input 스타일 수정한다.
- Search 화면에 맞게, TopNavBar 의 컴포넌트 스타일을 수정한다.
- Search 예상 피그마 시안과 동일하게 나올 것 이다. 다른 곳에도 동일한 스타일이 필요하여, 이부분 또한 수정하였다.
- 커밋 총 3개가 날라갈 예정입니다.
close : #65
> design: Search 메인화면 퍼블리싱 (#65)

- src/components/common/userItem/Follow/Follow.jsx
- Follow 컴포넌트에 버튼 토글 기능을 추가했습니다.
- 클릭할때마다 팔로우 버튼, 취소 버튼으로 바뀝니다.
close : #74
> design: Follow 컴포넌트 버튼 토글 기능 추가 (#74)

- package-lock.json
- package.json
- 캐러셀 구현 시 swiper 라이브러리를 사용하기 위해 모듈을 설치했습니다.
- swiper 라이브러리를 사용할 수 있습니다.
- pull을 받은 후 `npm i` 명령어를 입력해서 해당 모듈을 받아주세요.
close : #83
> [chore] swiper 라이브러리 사용을 위한 모듈 설치

- src/pages/EmailLoginPage/EmailLoginPage.jsx
- 추후 기능 개발시 유효성 검사 결과에 따라 버튼 비활성화/활성화를 적용하기 위해 미리 추가하였습니다.
- disable이 true일때는 비활성화, disable이 false일때는 활성화되어야 합니다.
close : #80
> [design] 이메일 로그인 페이지 내 로그인 버튼에 disabled 옵션 추가 (#80)

- src/pages/LoginMainPage/LoginMainPage.jsx
- 로그인 메인 화면을 구현했습니다.
- LoginMainPage.jsx 추가
- 코드리뷰 부탁드립니다,,
- 코드 수정 예정입니다.
close : #35
> design: 로그인 메인 화면 퍼블리싱 (#35)

- src/pages/ProfileModificationPage/ProfileModificationPage.jsx
- 프로필 수정 페이지를 구현했습니다.
- ProfileModificationPage.jsx 추가
- 어렵구만요,,
close : #82
> desing: 프로필 수정 페이지 퍼블리싱 (#82)

- src/pages/communityPage/CommunityLayout.jsx
- src/pages/communityPage/CommunityMainPage/CommunityMainPage.jsx
- src/pages/communityPage/CommunityMainPage/PopularPosts.jsx
- src/pages/communityPage/CommunityMenu.jsx
- 디자인 시안에 따라 커뮤니티(집사생활) 메인 페이지를 구현했습니다.
- 커뮤니티 메인 페이지 파일(CommunityMainPage.jsx)이 추가됩니다.
- 실시간 인기글 컴포넌트(PopularPosts.jsx)가 추가됩니다.
- 커뮤니티 메뉴 컴포넌트(CommunityMenu.jsx)가 추가됩니다.
close : #79
> design: 커뮤니티(집사생활) 메인 페이지 퍼블리싱 (#79)

- src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx
- 상품 등록 페이지를 구현했습니다.
- ProductRegistrationPage.jsx 추가
- 아직 없습니다!
close : #84
> design: 상품 등록 페이지 퍼블리싱 (#84)

- src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx
- border 오타 수정했습니다.
close : #104
> style: border 오타 수정 (#104)

- src/pages/communityPage/NotFoundLocation.jsx
- 커뮤니티 날씨, 동물병원 페이지에서 위치를 불러오지 못할 경우 보여주기 위해 NotFoundLocation 컴포넌트를 구현했습니다.
- 위치 정보를 불러오지 못할 경우 사용됩니다.
close : #110
> design: NotFoundLocation 컴포넌트 구현 (#110)

- src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
- src/pages/profilePage/ProfilePage.jsx
- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
- src/pages/yourProfilePage/YourHeader/YourHeader.jsx
- src/pages/yourProfilePage/YourPost/YourPost.jsx
- src/pages/yourProfilePage/YourProduct/YourProduct.jsx
- src/pages/yourProfilePage/YourProfilePage.jsx
- YourProfilePage 안에 YourHeader, YourPost, YourProduct 안의 세가지 영역으로 나누었습니다.
- swiper 라이브러리 사용하여 캐러셀 구현하였습니다
- 앨범형/리스트형을 따로 구현 후 리스트형을 주석처리 해두었습니다.
close : #64
> design: YourProfilePage 페이지 퍼블리싱(#64)

- src/pages/communityPage/CommunityLayout.jsx
- src/pages/communityPage/CommunityMainPage/CommunityMainPage.jsx
- src/pages/communityPage/CommunityMenu.jsx
- src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
- src/pages/communityPage/communityHospitalPage/CommunityHospitalDetailPage/CommunityHospitalDetailPage.jsx
- src/pages/communityPage/communityHospitalPage/CommunityHospitalMainPage/CommunityHospitaMainlPage.jsx
- 커뮤니티 페이지 TopNav, CommunityMenu를 디자인 시안에 맞춰 수정
- CommunityMenu : 사용자가 접속한 메뉴가 bold 처리됩니다.
- TopTitleNav 사용 페이지 : 더보기 버튼이 보이지 않습니다.
- TopMainNav 사용 페이지 : 검색 버튼이 보이지 않습니다.
close : #125
> design: 커뮤니티 페이지 TopNav, CommunityMenu 디자인 시안에 맞춰 수정 (#125)

- src/components/common/modal/CommentModal/CommentModal.jsx
- src/pages/PostDetailPage/PostComment.jsx
- 댓글과 모달 연결
- 댓글 더보기 버튼 클릭 시 CommentModal이 뜨도록 했습니다.
- 아래 부분은 테스트를 위해 넣어놓은 사항으로 기능 개발시 필요가 없다면 삭제하셔도 됩니다.
https://github.com/daengnyang-market/daengnyang-market-client/blob/62f790c982a75c8aef81ffb9a426b7771b68987e/src/pages/PostDetailPage/PostComment.jsx#L9
내 댓글인 경우 - 삭제
다른 사람의 댓글인 경우 - 신고
close : #138
> design: 댓글에 모달 연결 (#138)

- src/components/common/Post/Post.jsx
- src/components/common/modal/PostModal/PostModal.jsx
- 게시글과 모달 연결
- 더보기 이미지가 더보기 버튼으로 변경됩니다.
- 게시글 더보기 버튼 클릭 시 PostModal이 뜹니다.
- 아래 부분은 테스트를 위해 넣어놓은 사항으로 기능 개발시 필요가 없다면 삭제하셔도 됩니다.
https://github.com/daengnyang-market/daengnyang-market-client/blob/a8a79623fff78e2b60dc30e2d0bf41a7107bf40b/src/components/common/Post/Post.jsx#L10
내 게시글인 경우 - 삭제&수정
다른 사람의 게시글인 경우 - 신고
close : #137
> design: 게시글에 모달 연결 (#137)

- src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx
- 업로드한 이미지 미리보기 기능을 추가하기 위해서
close : #148
> feat: 업로드한 이미지 미리보기 기능 추가 (#148)

- src/App.jsx
- src/routes/Router.jsx
- 기능 개발에 앞서 용이한 개발을 위해 Router 파일을 추가하였습니다.
- Router 파일이 생성됩니다.
- Router 파일의 path를 입력하면 해당 url로 이동이 가능합니다.
https://github.com/daengnyang-market/daengnyang-market-client/blob/5e4f58b4a5909ac972bdc5d5fa049a41e4f6d454/src/routes/Router.jsx#L21-L41
- 해당 파일은 1차 작성본으로, 앞으로 꾸준한 수정이 필요할 것으로 예상됩니다.
- App.jsx에 Router를 추가하면서 마크업 부분을 수정했습니다.
- main 태그를 div로 바꿈 : main은 html 문서에서 한번만 사용 가능하지만 중복 사용되고 있어 div로 변경함
- styled-components명 변경 (`FrameMain`, => `MainContainer`)
- styled-components 코드를 파일 하단으로 이동했습니다.
close : #150
> add: Router 파일 추가 (#150)

- src/components/layout/ContentsLayout/FrameLayout.jsx
- src/components/layout/ContentsLayout/MainLayout.jsx
- App.jsx 내부 코드를 깔끔하게 하기 위해 레이아웃을 분리했습니다.
- App.jsx를 깔끔하게 유지할 수 있습니다.
- 각 페이지의 최상단 태그로 `<MainLayout>`이 들어가야 합니다.
- **App.jsx 파일은 아직 수정하지 않았습니다. 모든 페이지 반영이 완료되면 App.jsx 파일 내부 레이아웃 코드를 제거하겠습니다.**
close : #151
> design: App.jsx 내부 레이아웃 분리 (#151)

- src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
- src/pages/profilePage/ProfilePage.jsx
- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- profilePage에서 포스팅이 없을때의 화면을 구현하였습니다
- useState true/false 값으로 포스팅 여부를 전달하려고 했는데, 잘 작동이 되지 않아 일단 퍼블리싱만 완료한 상태입니다. 
close : #115
> design: profilePage에서 포스팅 없을때의 화면 퍼블리싱 (#115)

- src/pages/profilePage/ProfilePage.jsx
- ProfilePage 내의 ProfileHeader import 경로가 잘못되어있어서 수정했습니다.
close : #160
> style: ProfilePage 내의 ProfileHeader 경로 수정 (#160)

- src/pages/ChatRoomPage/ChatRoomPage.jsx
- src/pages/ChatRoomPage/ChatUploadComment.jsx
- src/pages/ChatRoomPage/MyChat.jsx
- src/pages/ChatRoomPage/UserChat.jsx
- 채팅 페이지 화면을 피그마 시안에 맞추어 렌더하고 싶어서 추가하였습니다.
- 
- 임의 값을 준 부분이 많기 때문에, 이는 참고하여 확인하시면 될 것 같습니다.
close : #108
> design: 채팅 페이지 퍼블리싱 (#108)

- src/pages/chatListPage/ChatList.jsx
- src/pages/chatListPage/ChatListPage.jsx
- src/routes/Router.jsx
- 채팅방 리스트 페이지를 퍼블리싱 했습니다. 리스트를 컴포넌트로 만들어서 이름,컨텐츠,날짜를 전달받을 수 있게 했습니다
close : #155
> style: 채팅방 리스트 퍼블리싱 (#155)

- src/pages/Error404Page/Error404Page.jsx
- 404 페이지 퍼블리싱했습니다
close : #168
> style: 404페이지 퍼블리싱 (#168)

- src/pages/ProductModificationPage/ProductModificationPage.jsx
- 상품 수정 페이지 퍼블리싱을 위해 추가했습니다.
- 어떻게 하면 상품 등록 페이지의 데이터를 가져올 수 있을지 계속 삽질해 봤는데 수확이 없었습니다. ㅠㅠ
- 때문에 현재는 아래와 같이 상품 등록 페이지와 동일한 상태입니다.
- 기능구현 때 다시 고민해서 수정해 보겠습니다. 
close : #107
> design: 상품 수정 페이지 퍼블리싱 (#107)

- src/pages/communityPage/CommunityLayout.jsx
- src/pages/communityPage/CommunityMainPage/CommunityMainPage.jsx
- src/pages/communityPage/CommunityMenu.jsx
- src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
- src/pages/communityPage/communityHospitalPage/CommunityHospitalDetailPage/CommunityHospitalDetailPage.jsx
- src/pages/communityPage/communityHospitalPage/CommunityHospitalMainPage/CommunityHospitaMainlPage.jsx
- src/pages/communityPage/communityHospitalPage/CommunityHospitalMainPage/HospitalList.jsx
- CommunityMenu와 각 커뮤니티 페이지 연결
- 커뮤니티 페이지 내부 서브 메뉴 클릭시 페이지 전환 가능
close : #179
> feat: CommunityMenu와 각 커뮤니티 페이지 연결 (#179)

- src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
- 팔로워/팔로잉 버튼 클릭시 FollowListPage로 이동하도록 추가했습니다! 
- 현재 FollowListPage 만 있어서 동일한 페이지를 연결했습니다. 
close : #184
> feat: 프로필페이지 팔로워/팔로잉버튼 클릭시 페이지 이동 (#184)

- src/pages/Error404Page/Error404Page.jsx
- src/routes/Router.jsx
- Router에 404페이지 연결되도록 추가했습니다.
- 유저가 이상한 경로 입력했을때 해당 페이지 뜰 예정
close : #185
> style: Router에 404page 추가 (#185)

- src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- [사용자가 업로드한 게시글] 섹션에서 목록형과 앨범형으로 게시글들을 확인할 수 있도록 작업했습니다
- 클릭했을때 아이콘 색상이 변경되는것은 추후 작업할 예정입니다.
close : #188
> feat: ProfilePost 리스트형/앨범형 버튼 구현

- src/pages/profilePage/ProfileHeader/MyProfileBtns.jsx
- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- 버튼 아이콘 바뀌는것만 구현되면 바로 머지하겠습니다
- 나의 프로필 페이지에서 프로필 수정 버튼을 클릭하면 내 프로필 수정 페이지로 이동하도록 구현 
- 나의 프로필 페이지에서 상품 등록 버튼을 클릭하면 상품 등록 페이지로 이동하도록 구현 
close : #190
> feat: ProfilePage - 나의 프로필 페이지에서 각각 버튼 연결 기능 구현

- src/components/common/Post/Post.jsx
- src/pages/FeedPage/FeedPage.jsx
- src/pages/SplashScreen/SplashScreen.jsx
- token값이 있는 경우 닉네임,아이디,컨텐츠,이미지를 Post 컴포넌트로 전달하여 화면에 출력
- token값 없을 경우 검색하기 화면 출력
- 사용자가 로그인을 했을 경우에는 팔로우한 사람의 피드를 볼 수 있다.
- 게시물이 없는 경우에는 검색하기 화면이 나오고, 버튼을 누르면 /search로 이동한다.
- 현재 Post 컴포넌트에 완벽하게 값이 전달되지 않습니다. (프로필 이미지,댓글 등) 추후 수정하겠습니다
close : #207
> feat: 홈(피드) 페이지 기능 구현 

- src/pages/SplashScreen/SplashScreen.jsx
- 토큰검증 후 valid값이 true가 나오면 gohome() 함수 실행되게 구현했습니다
- 로그인된 사용자는 메인페이지(Home)으로 이동
- 로그인 하지 않은 사용자는 로그인 페이지로 이동
- 현재 토큰값이 없어서 임시로 tempToken 에 제 토큰을 넣었습니다...! 
close : #202
> feat: splash page 기능구현 (#202)

- src/pages/SplashScreen/SplashScreen.jsx
- 토큰 없을 때 예외처리 추가
- 토큰 검증 후 FeedPage로 이동했을 때 발생하는 렌더링 에러 해결
- 토큰이 없을 때 401에러가 발생하지 않아야 합니다.
- 토큰 검증 후 FeedPage로 이동했을 때 렌더링 에러가 발생하지 않아야 합니다.
close : #213 #214
> fix: 토큰 없을 때 예외처리 추가 및 렌더링 에러 해결 (#213, #214)

- src/context/AuthContext.jsx
- src/pages/FeedPage/FeedPage.jsx
- src/pages/SplashScreen/SplashScreen.jsx
- 최초 로그인 후 FeedPage로 이동했을 때 401 에러 발생 해결
- 최초 로그인 후 FeedPage로 이동했을 때 401 에러가 발생하지 않아야 합니다.
- 원인 : 최초 렌더링 시에도 ajax 통신이 진행되어 토큰 검증 실패
- 해결 : token에 값이 있을때만 ajax 통신을 하도록 함
close : #214
> fix: 최초 로그인 후 FeedPage로 이동했을 때 401 에러 발생 현상 (#214 이슈 재오픈)

- src/pages/JoinMembershipPage/JoinMembershipInput.jsx
- 인풋요소를 대거 수정하면서 생긴, 스타일변화에 따라 원래 시안에 맞추어 다시 스타일 수정
- 피그마 시안과 동일한 디자인이 되었습니다.
- 확인부탁드려요~
close : #203
> design: 인풋 대거 수정으로 인한, 스타일 누락된 부분 수정 (#203)

- src/App.jsx
- src/components/common/modal/ProfileModal/ProfileModal.jsx
- src/context/AuthContext.jsx
- src/pages/EmailLoginPage/EmailLoginPage.jsx
- src/pages/FeedPage/FeedPage.jsx
- src/pages/SplashScreen/SplashScreen.jsx
- 최초 로그인 시 피드 게시물을 가져오지 못하는 현상 수정을 위해 토큰 로직 변경
- 최초 로그인 시 피드 게시물을 잘 가져옵니다.
- 이미 로그인된 경우에도 피드 게시물을 잘 가져옵니다.
- context명 수정으로 인해 token을 context에서 꺼내는 코드의 수정이 필요합니다. (현재까지 develop에 반영된 코드들은 수정 적용해놓았습니다.)
- 머지 후 사용 방법
1. `useContext` import한다.
2. `import { AuthContextStore } from '../../context/AuthContext'` 추가 (AuthContext의 경로는 페이지 위치에 따라 달라질 수 있습니다.)
3. `const { token } = useContext(AuthContextStore);`
close : #221
> fix: 최초 로그인 시 피드 게시물을 가져오지 못하는 현상 수정을 위해 토큰 로직 변경 (#221)

- src/components/common/TopNavBar/TopUploadNav.jsx
- 확장성을 위해 코드를 추가했습니다.
close : #224
> style: 확장성을 위한 코드 추가 (#224)

- src/pages/ProductRegistrationPage/ItemLinkInput.jsx
- src/pages/ProductRegistrationPage/ItemNameInput.jsx
- src/pages/ProductRegistrationPage/PriceInput.jsx
- src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx
- 상품 등록 페이지 기능 구현을 위해 추가했습니다.
- 각각의 input을 나누어 관리합니다.
- 토큰을 임시로 발급받아 구현했습니다.
close : #200
> feat: 상품 등록 페이지 기능 구현 (#200)

- src/components/common/ProfileImage/ProfileImage.jsx
- src/components/common/userItem/Search/Search.jsx
- src/components/common/userItem/UserAccountInfo/UserAccountInfo.jsx
- src/pages/SearchPage/SearchPage.jsx
- 유저 검색을 통하여, 원하는 유저를 찾아볼 수 있도록 기능을 구현하였습니다. 
- 유저의 리스트가 검색키워드에 맞추어 검색됩니다.
- 성능개선을 위해, 무한스크롤 혹은 버추얼스크롤을 추후에 시도할 예정입니다.
close : #205
> feat: 검색 기능 추가 (#205)

- src/components/common/TopNavBar/TopUploadNav.jsx
- 확장성을 위한 TopUploadNav.jsx 내부 코드 추가를 위해
- 없습니다.
close : #234
> style: 확장성을 위한 코드 추가 (#234)

- src/components/common/Animation/Animation.jsx
- src/components/common/Loading/Loading.jsx
- #237 이슈를 위해 수정한 파일 중 Animation 파일이 누락되어 추가
- Loading 컴포넌트 내 필요없는 div 삭제
- Animation 파일에 spin 애니메이션이 추가됩니다.
close : #237
> add: 누락된 Animation 파일 업로드 및 Loading 컴포넌트 마크업 수정 (#237)

- src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx
- 일부 누락되거나 변경내역을 수정했습니다.
close : #241
> style: 누락 및 변경내역 코드 수정 (#241)

- src/pages/PostUploadPage/ImageUploadButton.jsx
- src/pages/PostUploadPage/PostUploadDetail.jsx
- src/pages/PostUploadPage/PostUploadPage.jsx
- 게시물을 업로드하면 POST 요청을 통하여 데이터가 넘어가게끔 하기위해서 추가하였습니다.
- 게시물 데이터를 업로드할 수 있습니다. 
- 상태관리 에러 ( 아마 useState 관련사항 ) 은 추후에 리팩토링 혹은 버그를 찾아서 다시 이슈올리겠습니다~!
##스크린샷
close : #245
> feat: 게시물 업로드 기능 구현 (#245)

- src/components/common/TopNavBar/TopSearchNav.jsx
- src/pages/PostUploadPage/ImageUploadButton.jsx
- src/pages/PostUploadPage/PostUploadDetail.jsx
- src/pages/PostUploadPage/PostUploadPage.jsx
- src/pages/SearchPage/SearchPage.jsx
- 유저검색을 할때, 유저정보가 안뜨는 것을 고치기 위하여 변경하였습니다.
- 다시 유저 검색이 가능해졌습니다.
- 없습니다~!
close : #256
> bug: 검색기능 사용시 유저목록이 안뜨는 버그 수정 (#256)

- src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
- src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
- src/pages/profilePage/ProfilePage.jsx
- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- 팔로우/언팔로우 기능 추가했습니다.
- 그외 자잘한 코드들을 리팩토링 했습니다.
- 이제 팔로우/언팔로우 기능 잘 작동할겁니다.
close : #269
> feat: 프로필 페이지 세부 기능 추가(팔로우/언팔로우)

- src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
- src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
- src/pages/profilePage/ProfilePage.jsx
- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
- useEffect의 두번째 인자에 accountname을 추가해주어서 주소의 accountname이 변경될때마다 랜더링 되도록 해결했습니다
close : #270
> fix: 하단 TabNav 클릭시 프로필페이지 업데이트 안되는 버그 수정 (#270)

- src/components/carousel/MultiItemCarousel/multiItemCarousel.css
- src/components/common/Product/Product.jsx
- src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
- 이미지가 찌그러져 보기 안좋아 꽉차게 수정했습니다.
- 원하는 비율을 완벽하게 맞출수는 없지만, 찌그러짐 현상은 해결되었습니다.
테스트중 상품명이 길어지면 상품금액이 하단으로 내려오는 현상 수정 후 재커밋 예정
close : #285
> fix: 판매중인 상품의 이미지 찌그러짐 현상 해결 (#285)

- src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
- src/components/common/TopNavBar/TopUploadNav.jsx
- src/components/common/modal/ProductModal/ProductModal.jsx
- src/pages/ProductModificationPage/ProductModificationPage.jsx
- src/pages/ProductRegistrationPage/ItemLinkInput.jsx
- src/pages/ProductRegistrationPage/ItemNameInput.jsx
- src/pages/ProductRegistrationPage/PriceInput.jsx
- src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx
- src/routes/Router.jsx
- 상품 수정 페이지 및 ProductModal 컴포넌트 내 수정 기능 구현을 위해 추가 되었습니다.
- (상품을 클릭하면 모달창이 열리고) 수정을 클릭하면 해당 상품의 수정페이지로 이동할 수 있습니다.
- 정말 많은 삽질을 했습니다ㅠㅠ
- 현재 상품가격 input 창에 한글도 입력이 되는 버그가 있습니다. (이슈에 올리고 수정할 예정입니다.)
- 추후 수정 페이지 로딩 속도 향상을 위한 작업을 해보고자 합니다.
close : #262
> feat: 상품 수정 페이지 및 ProductModal 컴포넌트 내 수정 기능 구현 (#262)

- src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
- src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
- src/pages/profilePage/ProfilePage.jsx
나의 상품 클릭했을때는 모달 뜨게하고, 다른 사용자의 상품 클릭시 바로 사이트로 이동하게끔 수정했습니다.
close : #289
> feat: 다른사용자의 상품 클릭했을때 판매사이트로 이동하는 기능 추가 (#289)

- src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
- src/components/common/modal/ProductModal/ProductModal.jsx
- src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
- ProductModal 기능 추가를 했습니다.
- 내 상품을 클릭하면 모달창이 열리고 해당하는 기능을 사용할 수 있습니다.
- 웹사이트에서 상품 보기 클릭 시 새 창으로 열리도록 작업했습니다.
close : #296
> feat: ProductModal 기능 추가 (#296)

- src/components/common/Post/Post.jsx
- src/components/common/modal/PostModal/PostModal.jsx
* Home에서 postID를 props로 받아오게 수정하였습니다
* 받아온 postID 로 삭제, 신고 기능 추가했습니다.
* 신고가 완료되면 Alert창이 뜨게 구현했습니다.
* 사용자가 작성한 게시글인 경우 삭제, 수정 버튼이 나타난다.
* 다른 사용자가 작성한 게시글인 경우 신고 버튼이 나타난다.
- 게시물 수정페이지가 구현되면 수정 버튼 Link 태그에 추가하겠습니다.
close : #305
> feat: PostModal 삭제/신고 기능 구현 

- src/pages/PostDetailPage/PostDetailPage.jsx
- 게시물 클릭했을때, 임의로 설정해둔 postid 값의 게시물로만 이동하는 오류를 수정하기위해서 입니다.
- 각 게시물에 맞는 postid 가 useParams() 를 통해, 지정될 것 입니다.
- 확인부탁드려요~!
close : #292
> fix: 게시물 클릭했을때, 임의로 설정해둔 postid 값의 게시물로만 이동하는 오류 수정 (#292)

- src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
- Loading 화면시 LoadingWrapper 로 안감싸준 페이지들이 발견되어 추가해주었습니다. 
close : #311
> style: 누락된 LoadingWrapper 스타일 추가 (#311)

- src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
- 상품 가격 표시 기능을 개선했습니다.
close : #310
> feat: 상품 가격 표시 기능 개선 (#310)

- src/components/common/Post/Post.jsx
- src/components/common/modal/PostModal/PostModal.jsx
- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- src/routes/Router.jsx
- 자잘하게 코드가 중복 혹은 잘못 들어가있는경우 수정
- 이제 페이지가 정상적으로 작동될 것 입니다.
- 확인부탁드려요~!
close : #320
> fix: 게시물과 모달 작업시 발생한 자잘한 버그 수정 (#320)

- src/components/common/Post/Post.jsx
- src/components/common/modal/PostModal/PostModal.jsx
- src/pages/PostUploadPage/ImageUploadButton.jsx
- src/pages/PostUploadPage/PostUploadDetail.jsx
- 게시물 수정시 생기는 버그를 해결하기 위해서 추가및 변경하였습니다.
- 게시물의 수정이 잘 되어 보여질 것입니다.
- 사진 순서가 뒤죽박죽이긴한데, 이부분은 차차 수정하겠습니다~!
close : #319
> fix: 게시물 수정시 생기는 버그 (#319)

- src/pages/ProductRegistrationPage/PriceInput.jsx
- 상품 가격 입력창에 숫자만 입력받을 수 있도록 수정하였습니다.
-  상품 가격 입력창에 숫자만 입력 가능합니다.
- 없습니다.
close : #309
> fix: 숫자만 입력받을 수 있도록 수정 (#309)

- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- 앨범형/리스트형 버튼을 구현하기 위해 4개의 UseState 를 사용했었는데, 한개로 줄였습니다. 
`const [listBtn, setListBtn] = useState(true);`
- 앨범형 뷰에서 여러장의 이미지가 있을 경우 레이어 아이콘이 나오게 추가했습니다.
- 앨범형 뷰에서 썸네일 이미지 누르면 각각 게시물로 가게끔 수정 예정
close : #324
> refactor: ProfilePost 앨범형,리스트형  코드 리팩토링 (#324)

- src/components/common/modal/CommentModal/CommentModal.jsx
- src/pages/PostDetailPage/PostComment.jsx
- 댓글 삭제와 신고를 할 수 있도록, 사용자들에게 기능을 제공하기 위해서 추가하였습니다.
- 본인의 댓글은 삭제가 가능하고, 본인의 댓글이 아닌경우에는 신고가 가능합니다.
- 없습니다~!
close : #323
> feat: 댓글 삭제 및 신고기능 추가 (#323)

- src/components/common/Post/Post.jsx
- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- ProfilePost 폴더 및 파일 복구했습니다.
- Post 파일 내에 중복된 import 들을 수정했습니다
close : #335
> fix: 삭제된 ProfilePost 파일 복구 및 Post 파일 수정 

- src/pages/ProductRegistrationPage/PriceInput.jsx
- 판매 중인 상품뿐만 아니라 상품 수정, 등록 페이지에서도 가격 입력 시 콤마가 찍혀, 가시성을 높이고자 추가했습니다.
- 없습니다.
close : #328
> refactor: 가격 입력 시 콤마로 표시 하기 기능 추가 (#328)

- src/routes/AuthRoute.jsx
- src/routes/NonAuthRoute.jsx
- src/routes/Router.jsx
- 로그인 여부에 따른 페이지 접근제한 기능 구현을 위해 추가했습니다.
- 로그인 여부에 상관없이 접근 가능한 페이지
```
<Route path='*' element={<Error404Page />} />
<Route path='/notfound' element={<Error404Page />} />
```
- 로그인이 안된 경우에만 접근 가능한 페이지
```
<Route path='/' element={<SplashScreen />} />
<Route path='/login' element={<EmailLoginPage />} />
<Route path='/join' element={<JoinMembershipPage />} />
<Route path='/join/setprofile' element={<ProfileSettingsPage />} />
```
- 로그인이 된 경우에만 접근 가능한 페이지
```
<Route path='/home' element={<FeedPage />} />
<Route path='/search' element={<SearchPage />} />
<Route path='/profile' element={<ProfilePage />} />
<Route path='/profile/:accountname' element={<ProfilePage />} />
<Route path='/profile/edit' element={<ProfileModificationPage />} />
<Route path='/follow/:accountname/:type' …
```
> fix: 라우터 접근제한 기능 추가 (#252)

- src/pages/EmailLoginPage/EmailLoginPage.jsx
- 이메일로 회원가입 페이지로 이동 기능을 추가하기 위해 수정했습니다.
- 로그인 페이지에서 이메일로 회원가입 페이지 링크 클릭 시, 회원가입 페이지로 이동됩니다.
- 버그 수정 테스트 완료
close : #356
> feat: 이메일로 회원가입 페이지로 이동 기능 추가 (#356)

- src/pages/ChatRoomPage/ChatRoomPage.jsx
- src/pages/ChatRoomPage/ChatUploadComment.jsx
- src/pages/ChatRoomPage/MyChat.jsx
- src/pages/ChatRoomPage/UserChat.jsx
- src/pages/chatListPage/ChatList.jsx
- src/pages/chatListPage/ChatListPage.jsx
- src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
- src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
- src/pages/profilePage/ProfilePage.jsx
- 채팅 기능을 추가하기 위해 코드 변경 및 추가하였습니다.
- 채팅기능을 사용가능합니다.
- 읽음표시 활용방안이 아직 알 수 없습니다.
close : #348
> feat: 채팅 기능 추가 (#348)

- src/pages/ChatRoomPage/MyChat.jsx
- src/pages/ChatRoomPage/UserChat.jsx
- src/pages/chatListPage/ChatList.jsx
- src/pages/chatListPage/ChatListPage.jsx
- src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
- 원활한 채팅 서비스를 위해 추가하였습니다.
- 일단 기본적인 기능은 가능해졌을겁니다.
- 일단 채팅기능 사용을 위해 확인부탁드려요~ 추후에 발생하는 버그는 따로 모아서 이슈로 만들겠습니다.
close : #375
> fix: 초기 채팅리스트 랜더오류,서버채팅 토큰 미설정 오류 및 시간미설정 (#375)

- src/pages/ChatRoomPage/ChatRoomPage.jsx
- src/pages/chatListPage/ChatList.jsx
- 대화룸에 입장을 하면, 시간역순으로 나열되어 보여진다. 이를 수정하기 위해 코드를 변경하였습니다.
- 제대로 나열되어 보일것입니다.
- 머지되면 테스트부탁드려용~
close : #380
> fix: 대화 역순으로 나열되는 버그 수정 (#380)

- src/pages/ProfileModificationPage/ProfileModificationPage.jsx
- src/pages/ProfileSettingsPage/InputAccountName.jsx
- src/pages/ProfileSettingsPage/ProfileInfo.jsx
- 기존 계정 ID로 입력 시 발생하는 오류 수정 및 불필요한 코드 삭제를 했습니다.
- 기존 계정 ID를 다시 입력해도 유효성 검사 오류가 발생하지 않습니다.
- 현재 계정 ID를 수정하면 프로필 페이지에서 에러가 발생합니다. (프로필 페이지에 대한 수정 필요)
close : #261
> fix: 기존 계정 ID로 입력 시 발생하는 오류 수정 및 불필요한 코드 삭제 (#261)

- src/components/common/modal/ProductModal/ProductModal.jsx
- 상품 삭제시 바로 업데이트가 되질 않아서, 삭제버튼 누르면 모달 닫힌 후 새로고침 되게 수정했습니다
close : #366
> fix: 상품 삭제시 새로고침 이벤트 추가 (#366)

- src/pages/ProfileSettingsPage/ProfileInfo.jsx
- 상품 수정 및 등록 페이지와 동일하게, 프로필 세팅 및 수정 페이지를 이미지 리사이징을 추가하여 리팩토링했습니다.
- 이미지 리사이징 코드가 추가 되어 비교적 용량이 큰 이미지도 업로드가 가능합니다.
- 머지 이후에 평소에 업로드가 잘되지 않았던 파일로 확인해 보시고 피드백 부탁드립니다!
close : #384
> refactor: 이미지 리사이징을 위한 코드 추가 (#384)

- src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
- 타 유저 프로필에서 채팅기능 클릭했을시, 채팅방이 존재하면 알림창이 안뜨는 버그를 수정하였습니다.
- 타 유저 프로필에서 기존 채팅방의 유무에 따라 채팅 생성이 결정됩니다.
- 한번 확인부탁드려용~!
close : #395
> fix: 타 유저 프로필에서 채팅기능 클릭했을시, 채팅방이 존재하면 알림창이 안뜨는 버그 수정 (#395)

- src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
- src/components/common/modal/ProductModal/ProductModal.jsx
- src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
- 다른 컴포넌트의 불필요한 렌더링을 막고 업데이트되어야 할 컴포넌트만 리렌더링 될 수 있도록 수정했습니다.
- 상품 삭제 시 판매 중인 상품의 업데이트 속도가 빨라졌습니다.
- 없습니다.
기존(좌) / 수정(우)
close : #402
> refactor: 판매 중인 상품 삭제 시 발생하는 렌더링에 대한 리팩토링 (#402)

- src/components/LikeBtn/LikeBtn.jsx
- src/components/common/Post/Post.jsx
- 선택과제였던 좋아요 기능을 추가했습니다.
- 게시물에 좋아요를 누를 수 있습니다!
https://user-images.githubusercontent.com/96304623/210155380-e7a4da8f-5e9b-4a7a-a75c-82818b23e813.mov
생각보다 너무 빨리 구현해서 느낌이 이상합니다. 버그가 있을 수도 있으니 찾으시면 말씀 부탁드립니다
close : #410
> feat: 게시물 좋아요기능 구현 (#410)

- src/pages/profilePage/ProfilePost/ProfilePost.jsx
- 프로필 포스트가 10개까지만 받아와져서, 무한스크롤을 구현하여 해결하였습니다.
- 이제 사용자의 프로필 포스트를 전부 볼 수 있습니다.
Done,setDone useState를 잘 활용하여 무한요청을 방지했습니다. 
https://user-images.githubusercontent.com/96304623/210060431-4727f0b4-286b-4fff-9fb8-3b63df619b96.mov
close : #397
> fix: 프로필 포스트 10개만 받아와지는 현상 무한스크롤 구현으로 해결 (#397)

- src/pages/ProfileSettingsPage/ProfileInfo.jsx
- src/pages/ProfileSettingsPage/ProfileSettingsPage.jsx
- 초기 프로필 설정 시에 Enter 입력으로도 '가져도댕냥 시작하기' 버튼 클릭과 동일한 효과를 주기 위해서 코드를 추가했습니다.
- 초기 프로필 설정 시에 Enter 입력으로도 '가져도댕냥 시작하기' 버튼 클릭과 동일한 효과를 주어, 사용자가 각 input 창에 대해 올바른 값을 입력한 후, Enter를 누르면 회원가입이 완료되고, 초기 화면으로 이동합니다.
- 없습니다.
close : #419
> refactor: Enter 이벤트를 위한 코드 추가 및 불필요한 코드 삭제 (#419)

- src/pages/EmailLoginPage/EmailLoginInput.jsx
- src/pages/EmailLoginPage/EmailLoginPage.jsx
- EmailLoginPage 코드 리팩토링을 위한 변경
- 사용하지 않는 useRef() 코드가 삭제됩니다.
- 전개 구문을 이용해서 데이터를 한 번에 객체 형태로 반환받도록 했습니다.
close : #431
> refactor: 사용하지 않는 ref 삭제 및 전개 구문을 이용한 코드 간략화 (#431)

- src/components/common/modal/ChatRoomModal/ChatRoomModal.jsx
- src/pages/chatListPage/ChatListPage.jsx
- 채팅방 나가기 버튼을 추가하기 위해서 변경하였습니다.
- 나가길 원하는 채팅방을 나갈 수 있습니다.
- 확인부탁드려요~!
close : #420
> feat: 채팅방 나가기 기능 추가 (#420)

- src/pages/PostUploadPage/ImageUploadButton.jsx
- src/pages/PostUploadPage/PostUploadDetail.jsx
…#438)
- 게시물 작성 시, 3장 이상 이미지를 업로드 할 때 alert 창은 뜨지만 업로드할 이미지는 계속 추가되는 현상을 수정하기 위하여 변경하였습니다.
- 정상적으로 3장까지만 업로드 가능합니다.
- 확인부탁드려요~!
close : #438
> fix: 게시물 작성 시, 3장 이상 이미지를 업로드 할 때 alert 창은 뜨지만 업로드할 이미지는 계속 추가되는 현상 (#438)

- src/components/common/Comment/Comment.jsx
- src/components/common/Modal/ChatRoomModal/ChatRoomModal.jsx
- src/components/common/Modal/CommentModal/CommentModal.jsx
- src/pages/ChatPage/ChatListPage/ChatList.jsx
- src/pages/ChatPage/ChatListPage/ChatListPage.jsx
- src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
- src/pages/ChatPage/ChatRoomPage/ChatUploadComment.jsx
- src/pages/PostPage/PostUploadPage/ImageUploadButton.jsx
- src/pages/PostPage/PostUploadPage/PostUploadDetail.jsx
- 담당했던 기능 파일 변수명을 직관적인 이름으로 수정 및 node 에서 발생하는 warning 해결을 위한 코드 수정을 하였습니다.
- 담당했던 기능 파일 변수명을 직관적인 이름으로 수정 및 node 에서 발생하는 warning 해결을 하여, 조금 더 깔끔해지고 명확한 코드가 되었습니다.
- 확인부탁드려요~!
close : #447
> cleanup: 담당했던 기능 파일 변수명을 직관적인 이름으로 수정 및 node 에서 발생하는 warning 해결

- src/components/common/Modal/ChatRoomModal/ChatRoomModal.jsx
- src/components/common/TopNavBar/TopTitleNav.jsx
- src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
- 채팅방 삭제 버튼 모달이 정상적으로 작동하지 않는 버그 발견하여 이를 수정하고자 코드를 추가 및 변경하였습니다.
- 정상적으로 모달이 작동합니다.
- 확인부탁드려요~!
close : #449
> fix: 채팅방 삭제 버튼 모달이 정상적으로 작동하지 않는 버그 수정
